// Generated by LiveScript 1.5.0
(function(){
  var slice$ = [].slice;
  module.exports = [
    setCount(function(){
      var that;
      return this.count = (that = this.options.maxCount) != null
        ? min(that, this.results.length)
        : this.results.length;
    }), setResults(function(){
      this.searchResults.sorted = sortWith(this.searchResults.sortFunc, this.results);
      return this.searchResults.sliced = slice$.call(this.searchResults.sorted, 0, count);
    })
  ];
}).call(this);
