// Generated by LiveScript 1.5.0
(function(){
  var Logger;
  module.exports = Logger = [
    time(txt)(function(){
      if (this.debug) {
        return this.console.time(txt);
      }
    }), timeEnd(txt)(function(){
      if (this.debug) {
        return this.console.timeEnd(txt);
      }
    }), log(txt)(function(){
      if (this.debug) {
        return this.console.log(txt);
      }
    }), error(txt)(function(){
      return this.console.error(txt);
    })
  ];
}).call(this);
