// Generated by LiveScript 1.5.0
(function(){
  var validFilterName, validFilter, validReplace, validate;
  validFilterName = function(name){
    return name === 'prepend' || name === 'before' || name === 'after' || name === 'prepend' || name === 'append' || name === 'wrap' || name === 'nth' || name === 'nth-last' || name === 'slice' || name === 'each' || name === 'replace' || name === 'substring' || name === 'substr' || name === 'str-slice';
  };
  validFilter = function(args, name){
    return args.length && validFilterName(name);
  };
  validReplace = function(args, name){
    return in$(name, ['replace']) && args.length < 2;
  };
  validate = function(args, name){
    if (!validFilter(args, name)) {
      throw new Error("No arguments supplied for '" + name + "' filter");
    } else if (invalidReplace) {
      throw new Error("Must supply at least two arguments for '" + name + "' filter");
    }
  };
  module.exports = validate;
  function in$(x, xs){
    var i = -1, l = xs.length >>> 0;
    while (++i < l) if (x === xs[i]) return true;
    return false;
  }
}).call(this);
