// Generated by LiveScript 1.5.0
(function(){
  module.exports = [
    parseArgs(function(){
      var options, positional, debug, e;
      try {
        options = parseOptions(this.args), positional = options._, debug = options.debug;
        this.options = options;
        this.actions = this.opts.actions;
        this.positional = positional || [];
        return this.debug = debug;
      } catch (e$) {
        e = e$;
        this.error(e.message);
        this.exit(2);
      }
    }), validateArgs(function(){
      if (this.args == null) {
        this.error('Error: Must specify arguments.');
        this.exit(2);
      }
    }), extractOpts(function(){
      this.options.displayFilename = getDisplayFilename(this.options, this.targets);
      this.exts = this.options.extensions;
      this.exclude = this.options.exclude;
      return this.callCallback = !this.options.quiet && !this.options.json && !this.options.to && !this.options.inPlace;
    })
  ];
}).call(this);
