// Generated by LiveScript 1.5.0
(function(){
  module.exports = [
    startDebug(function(){
      this.time('everything');
      this.log('options:');
      return this.log(options);
    }), endDebug(function(){
      this.timeEnd('parse-selector');
      this.log('parsed-selector:');
      return this.log(JSON.stringify(this.parsed.selector, null, 2));
    })
  ];
}).call(this);
