// Generated by LiveScript 1.5.0
(function(){
  module.exports = [
    searchInput(function(){
      if (!this.input) {
        return;
      }
      this.search('(input)', this.input);
      this.resultsFormat = this.search.resultsFormat;
      return this.end(['-']);
    }), searchTargets(function(){
      var cwd;
      cwd = process.cwd();
      async.eachSeries(this.targets, searchTarget(cwd, cwd), function(){
        return end(this.targetPaths);
      });
    }), doSearch(function(){
      this.targetPaths = [];
      return this.searchInput() || this.searchTargets();
    }), prepareSearch(function(){
      return this.search = new Search({
        console: this.console,
        parsed: this.parsed,
        parserOptions: this.parserOptions,
        callback: this.callback,
        callCallback: this.callCallback,
        options: this.options,
        actions: this.actions,
        opts: this.opts
      });
    })
  ];
}).call(this);
