// Generated by LiveScript 1.5.0
(function(){
  var slice$ = [].slice;
  module.exports = [
    parseSelector(function(){
      this.parsed == null && (this.parsed = {});
      this.time('parse-selector');
      return this.parsed.selector = this.queryEngine.parse(this.selector);
    }), selectorFromFile(function(){
      var e;
      try {
        this.selector = this.fs.readFileSync(that, 'utf8');
      } catch (e$) {
        e = e$;
        this.error("Error: No such file '" + this.options.file + "'.");
        this.exit(2);
        return;
      }
      return this.targets = this.positional;
    }), selectorFromPos(function(){
      this.selector = this.positional[0];
      return this.targets = slice$.call(this.positional, 1);
    })
  ];
}).call(this);
