// Generated by LiveScript 1.5.0
(function(){
  var ref$, getFilters, getArgs, getRaw, getOrigResults, replacer, unlines, lines, ReplaceNode, replace;
  ref$ = require('./utils'), getFilters = ref$.getFilters, getArgs = ref$.getArgs, getRaw = ref$.getRaw;
  getOrigResults = require('./orig-results').getOrigResults;
  replacer = require('./replacer').replacer;
  ref$ = require('prelude-ls'), unlines = ref$.unlines, lines = ref$.lines;
  ReplaceNode = './replace-node'.ReplaceNode;
  replace = function(replacement, input, nodes, queryEngine, actions){
    var replaceNode;
    replaceNode = new ReplaceNode(replacement, input, nodes, queryEngine, actions);
    replaceNode.iterate();
    return unlines(replaceNode.inputLines);
  };
  module.exports = {
    replace: replace
  };
}).call(this);
