// Generated by LiveScript 1.5.0
(function(){
  var ref$, getFilters, getArgs, getRaw, getOrigResults, replacer, unlines, lines, createReplaceNodes, replace;
  ref$ = require('./utils'), getFilters = ref$.getFilters, getArgs = ref$.getArgs, getRaw = ref$.getRaw;
  getOrigResults = require('./orig-results').getOrigResults;
  replacer = require('./replacer').replacer;
  ref$ = require('prelude-ls'), unlines = ref$.unlines, lines = ref$.lines;
  createReplaceNodes = './replace-nodes'.createReplaceNodes;
  replace = function(replacement, input, nodes, queryEngine, actions){
    var replaceNodes;
    replaceNodes = createReplaceNodes(replacement, input, nodes, queryEngine, actions);
    replaceNodes.iterate();
    return unlines(replaceNodes.inputLines);
  };
  module.exports = replace;
}).call(this);
