// Generated by LiveScript 1.5.0
(function(){
  var replacer, filterRegex, hasFilter, parseFilters, extract, useReplacementFunc, createReplacementFunc, isFun, getReplacementFunc, slice$ = [].slice, toString$ = {}.toString;
  replacer = require('./replacer').replacer;
  filterRegex = /\s+\|\s+([-a-zA-Z]+)((?:\s+(?:'(?:\\'|[^'])*'|"(?:\\"|[^"])*"|[^\|\s]+))*)/;
  hasFilter = function(txt){
    return /^\s*\|\s+/.test(txt);
  };
  parseFilters = function(filterStr, actions){
    var ref$, filters, selector;
    filterStr = filterStr.trim();
    if (typeof hasFilter == 'function' && hasFilter(filterStr)) {
      return ref$ = (" " + filterStr).split(filterRegex), filters = slice$.call(ref$, 1), ref$;
    } else {
      return ref$ = filterStr.split(filterRegex), selector = ref$[0], filters = slice$.call(ref$, 1), ref$;
    }
  };
  extract = function(replacement, actions){
    return parseFilters(replacement, actions);
  };
  useReplacementFunc = function(replacement, input, queryEngine){
    return function(node){
      return replacement(function(it){
        return getRaw(input, it);
      }, node, function(it){
        return queryEngine.query(it, node);
      }, node._named);
    };
  };
  createReplacementFunc = function(replacement, input, queryEngine, actions){
    var replacementPrime;
    replacementPrime = replacement.replace(/\\n/g, '\n');
    return function(node){
      var replaceFun;
      replaceFun = replacer(input, node, queryEngine, actions);
      return replacementPrime.replace(/{{}}/g, function(){
        return getRaw(input, node);
      }).replace(/{{((?:[^}]|}[^}])+)}}/g, replaceFun);
    };
  };
  isFun = function(fun){
    return toString$.call(fun).slice(8, -1) === 'Function';
  };
  getReplacementFunc = function(replacement, input, queryEngine, actions){
    var createFun;
    createFun = typeof isFun == 'function' && isFun(replacement) ? useReplacementFunc : createReplacementFunc;
    return createFun(replacement, input, queryEngine, actions);
  };
  module['export'] = [getReplacementFunc, extract];
}).call(this);
