// Generated by LiveScript 1.5.0
(function(){
  var replacer, useReplacementFunc, createReplacementFunc, isFun, getReplacementFunc, toString$ = {}.toString;
  replacer = require('./replacer').replacer;
  useReplacementFunc = function(replacement, input, queryEngine){
    return function(node){
      return replacement(function(it){
        return getRaw(input, it);
      }, node, function(it){
        return queryEngine.query(it, node);
      }, node._named);
    };
  };
  createReplacementFunc = function(replacement, input, queryEngine, actions){
    var replacementPrime;
    replacementPrime = replacement.replace(/\\n/g, '\n');
    return function(node){
      return replacementPrime.replace(/{{}}/g, function(){
        return getRaw(input, node);
      }).replace(/{{((?:[^}]|}[^}])+)}}/g, replacer(input, node, queryEngine, actions));
    };
  };
  isFun = function(fun){
    return toString$.call(fun).slice(8, -1) === 'Function';
  };
  getReplacementFunc = function(replacement, input, queryEngine, actions){
    var createFun;
    createFun = typeof isFun == 'function' && isFun(replacement) ? useReplacementFunc : createReplacementFunc;
    return createFun(replacement, input, queryEngine, actions);
  };
  module['export'] = {
    getReplacementFunc: getReplacementFunc
  };
}).call(this);
