// Generated by LiveScript 1.5.0
(function(){
  var levn, getArgs, getRaw;
  levn = require('levn');
  getArgs = function(filters){
    var argsStr;
    argsStr = filters.shift().trim();
    argsStr += filters.shift();
    return levn.parse('Array', argsStr);
  };
  getRaw = function(input, node){
    var raw, that, prependStr, appendStr;
    raw = (that = node.raw)
      ? that
      : node.start != null
        ? input.slice(node.start, node.end)
        : node.key != null && node.value != null ? input.slice(node.key.start, node.value.end) : '';
    node.raw = raw;
    prependStr = node.rawPrepend || '';
    appendStr = node.rawAppend || '';
    return prependStr + "" + raw + appendStr;
  };
  module.exports = [getRaw, getArgs];
}).call(this);
