// Generated by LiveScript 1.5.0
(function(){
  var levn, filterRegex, getArgs, hasFilter, parseFilters, parseFilterObj, getFilters, getRaw, slice$ = [].slice;
  levn = require('levn');
  filterRegex = /\s+\|\s+([-a-zA-Z]+)((?:\s+(?:'(?:\\'|[^'])*'|"(?:\\"|[^"])*"|[^\|\s]+))*)/;
  getArgs = function(filters){
    var argsStr;
    argsStr = filters.shift().trim();
    argsStr += filters.shift();
    return levn.parse('Array', argsStr);
  };
  hasFilter = function(txt){
    return /^\s*\|\s+/.test(txt);
  };
  parseFilters = function(filterStr){
    var ref$, filters, selector;
    filterStr = filterStr.trim();
    if (typeof hasFilter == 'function' && hasFilter(filterStr)) {
      return ref$ = (" " + filterStr).split(filterRegex), filters = slice$.call(ref$, 1), ref$;
    } else {
      return ref$ = filterStr.split(filterRegex), selector = ref$[0], filters = slice$.call(ref$, 1), ref$;
    }
  };
  parseFilterObj = function(filterArg, actions){
    return filterArg;
  };
  getFilters = function(filterArg, actions){
    if (deepEq$(typeof filterArg, 'string', '===')) {
      return parseFilters(filterArg);
    } else {
      return parseFilterObj(filterArg, actions);
    }
  };
  getRaw = function(input, node){
    var raw, that, prependStr, appendStr;
    raw = (that = node.raw)
      ? that
      : node.start != null
        ? input.slice(node.start, node.end)
        : node.key != null && node.value != null ? input.slice(node.key.start, node.value.end) : '';
    node.raw = raw;
    prependStr = node.rawPrepend || '';
    appendStr = node.rawAppend || '';
    return prependStr + "" + raw + appendStr;
  };
  module.exports = {
    getRaw: getRaw,
    getFilters: getFilters,
    getArgs: getArgs
  };
  function deepEq$(x, y, type){
    var toString = {}.toString, hasOwnProperty = {}.hasOwnProperty,
        has = function (obj, key) { return hasOwnProperty.call(obj, key); };
    var first = true;
    return eq(x, y, []);
    function eq(a, b, stack) {
      var className, length, size, result, alength, blength, r, key, ref, sizeB;
      if (a == null || b == null) { return a === b; }
      if (a.__placeholder__ || b.__placeholder__) { return true; }
      if (a === b) { return a !== 0 || 1 / a == 1 / b; }
      className = toString.call(a);
      if (toString.call(b) != className) { return false; }
      switch (className) {
        case '[object String]': return a == String(b);
        case '[object Number]':
          return a != +a ? b != +b : (a == 0 ? 1 / a == 1 / b : a == +b);
        case '[object Date]':
        case '[object Boolean]':
          return +a == +b;
        case '[object RegExp]':
          return a.source == b.source &&
                 a.global == b.global &&
                 a.multiline == b.multiline &&
                 a.ignoreCase == b.ignoreCase;
      }
      if (typeof a != 'object' || typeof b != 'object') { return false; }
      length = stack.length;
      while (length--) { if (stack[length] == a) { return true; } }
      stack.push(a);
      size = 0;
      result = true;
      if (className == '[object Array]') {
        alength = a.length;
        blength = b.length;
        if (first) {
          switch (type) {
          case '===': result = alength === blength; break;
          case '<==': result = alength <= blength; break;
          case '<<=': result = alength < blength; break;
          }
          size = alength;
          first = false;
        } else {
          result = alength === blength;
          size = alength;
        }
        if (result) {
          while (size--) {
            if (!(result = size in a == size in b && eq(a[size], b[size], stack))){ break; }
          }
        }
      } else {
        if ('constructor' in a != 'constructor' in b || a.constructor != b.constructor) {
          return false;
        }
        for (key in a) {
          if (has(a, key)) {
            size++;
            if (!(result = has(b, key) && eq(a[key], b[key], stack))) { break; }
          }
        }
        if (result) {
          sizeB = 0;
          for (key in b) {
            if (has(b, key)) { ++sizeB; }
          }
          if (first) {
            if (type === '<<=') {
              result = size < sizeB;
            } else if (type === '<==') {
              result = size <= sizeB
            } else {
              result = size === sizeB;
            }
          } else {
            first = false;
            result = size === sizeB;
          }
        }
      }
      stack.pop();
      return result;
    }
  }
}).call(this);
